version: '3.9'

services:

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: postgres 
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 

  liquibase:
    image: liquibase/liquibase:4.23
    container_name: liquibase
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./database/sql/liquibase/changelog/:/liquibase/changelog
    command: update --changelog-file=changelog-1.sql --url=jdbc:postgresql://database:5432/postgres --username=username --password=password

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8090:80"
    depends_on:
      database:
        condition: service_healthy 

  api:
    container_name: api
    ports:
      - 4002:4002
    build: ./api/.
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: frontend
    ports: 
      - 5000:5000
    build: ./flutter_calendar/.
    depends_on:
      - api
      - database
