version: '3'

services:

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8090:80"

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: postgres 
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  liquibase:
    image: liquibase/liquibase:4.23
    container_name: liquibase
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./sql/liquibase/changelog/:/liquibase/changelog
    command: update --changelog-file=changelog-1.sql --url=jdbc:postgresql://database:5432/postgres --username=username --password=password