service: calendar-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getUsers:
    handler: users.handler
    timeout: 60
    events:
      - httpApi:
          path: /users
          method: get
  getSchedules:
    handler: schedules.handler
    timeout: 60
    events:
      - httpApi:
          path: /schedules
          method: get
  getEvents:
    handler: events.handler
    timeout: 60
    events:
      - httpApi:
          path: /events
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4002